### PR TITLE
accept combinator now filters on content-type

### PR DESCRIPTION
**Pull request by nuttycom**
Previously, we didn't have any combinator that allowed the server to dispatch based upon content type, though this seemed the obvious thing for the accept combinator to do. Now it does so.

### CODE REVIEW

**Comment by nuttycom** [comment]
review by @jdegoes @dchenbecker

**Comment by jdegoes** [comment]
+1

We do need to think, what's a combinator that can be used to only process content of a given type? That was the old job of the accept combinator. It's logical contentType() be used for that, although that's overloaded now to mean something it shouldn't.

**Comment by jdegoes** [comment]
Btw, I like that produce checks accept headers, it's a perfect match -- this allows you to put lots of different produce headers, and rely on the combinator to do the right thing, matching the first one that produces a content type acceptable to the client.

**Comment by nuttycom** [comment]
The accept combinator still does that; it just now can check more than one
content type at once, for the case where you have a single handler that
works with multiple content types. The only real change is from equality to
set inclusion (for accept) - and so of course it can still serve the way it
did previously by just passing a single type.

**Pull request merged**
