### PR TITLE
Topic/parser io

### PR DESCRIPTION
**Pull request by non**
This introduces AsyncParser, a class with a feed method accepting an optional ByteBuffer and returning a sequence of Validation[Throwable, JValue]. It also contains a bunch of tests of AsyncParser's correctness.

### CODE REVIEW

**Comment by non** [comment]
So I guess the implication is that if there are any parse errors you don't get any results? I had structured it the other way because it seemed like we wanted to try to support error-recovery. For example, you might get 3 JValues, an Exception, then 2 more JValues. It's easier if we just want to give up after a parse error though!

**Comment by non** [comment]
Well, we need an object because when you're parsing asynchronously you might end up with leftovers. I suppose we could have some kind of state object that gets passed in and then returned with the results if you want.

**Comment by jdegoes** [comment]
Ah, good point. Probably, it's better to have a fine level of granularity, e.g. Seq[Validation[Throwable, JValue]]. This is a lot of per value boxing (much more than ValidationNel[Throwable, Seq[JValue]]) but does permit the client to determine if failure to parse a single value is a total failure or not.

**Comment by jdegoes** [comment]
You do need an object, but (1), the object can be created from a call to parseAsync, so users know where to look for the methods (all the parse methods are in JParser, it's non-standard to introduce a new parsing method which requires the user to know about and create a class; better to have a helper funciton in JParser to create the AsyncParser), and (2) the interface can theoretically be pure (the easiest way to do that is the bundle state information so you can copy it prior to any parsing and return the new async parser with the new mutated state).

**Comment by non** [comment]
OK, fair enough. I guess the question is, do you want state to be referentially transparent? If so, then I think there will potentially be some performance overhead, as right now we can use our state as a scratch pad. If not, then of course this will be an improvement.

Let me know how you want to proceed.

**Comment by jdegoes** [comment]
State doesn't need to be referentially transparent as long as you copy it before invoking the "feed" logic. The client only sees the state between invocations of feed. So if you copy it prior to the internal logic of feed, and return the new async parser with the copied & mutated state, it's still externally referentially transparent. Let me know if you'd like me to elaborate / pair.

**Comment by non** [comment]
No I see that. I'm not sure what impact the copying will have, hopefully not much. I'll submit a revised version soon.

**Comment by non** [comment]
Hi John, this commit should address your concerns. I included some timing information in the commit message. Let me know if there are any other changes you'd like to see.

**Comment by non** [comment]
Alright, I think with these changes it should be in a good enough state to go in. We do use the Mealy machine abstraction, with two versions of parseAsync. The first, where you don't have an AsyncParser yet, builds one for you. The other uses the one you provide.

Error recovery searchers for newlines as per our discussion. In the future we can try to do something fancier but based on what Daniel told me today, I don't think that there is a straightforward general way to proceed (it seems like most error recovery is just about finding _more errors_ not about trying to guarantee correct parsing).

There is some error recovery testing also.

**Comment by non** [comment]
OK, should have these changes done very quickly.

**Pull request merged**
