### PR TITLE
Reinstate mock mongo

### PR DESCRIPTION
**Pull request by noelwelsh**
Prior to this commit, mocking was done on a individual class-by-class
basis. This has two problems:
1. It isn't extensible, as BlueEyesServiceSpecification needs to know
   about all mockable classes
2. It doesnt' work now that code is split across different projects.
   In particular, Mongo isn't in the same project as
   BlueEyesServiceSpecification

This change introduces a global mock configuration. The semantics are
thus:
- If a per-class key is set, use the value of that key to determine
  if that class should be mocked;
- Otherwise, inspect the value of the global key

The MockConfiguration object handles manipulating the global key and
implementing the semantics above.

Upated BlueEyesServiceSpecification, ConfigurableMongo and
ConfigurableHttpClient to use this system.

### CODE REVIEW

**Comment by noelwelsh** [comment]
This is not a complete solution. There is a race condition I'm seeing:

Let's say test A and test B both use the mock Mongo. Test A start running first, sees that the global key isn't set and sets it. Test B starts, sees the global key is set and leaves it alone. Test A finishes and resets the key to an empty value. A test in test B inspects the key and decides to create a real Mongo... exceptions ensure. I see this even when I set parallelExecution := false in SBT.

Perhaps the value of mock switches should be single assigment only for the lifetime of a JVM? So once the value is set (either by explicitly setting it, or finding a value in the environment) it never changes. What do you guys think?

**Comment by jdegoes** [comment]
Hi Noel,

I'd love to make you a committer on BlueEyes. We've had a chance to get to know you and admire your work. 

What do you think?

Regards,

John

**Comment by noelwelsh** [comment]
That would be great! How do you want to coordinate development? At the
moment it seems all the dev. discussion takes place off-list -- in the
offices of Reportgrid I assume. This makes it hard for me to know what
direction BlueEyes is taking so I'm not comfortable committing more
than bug fixes without some review. It would be better for the
community if more discussion took place on the list, and would make it
easier for me (and others!) to contribute.

N.

On Mon, Feb 13, 2012 at 10:33 PM, John A. De Goes
reply@reply.github.com
wrote:

**Comment by noelwelsh** [comment]
For the record, I confused environment variables and system properties in the above. I should revert e5c94b7. I now think the mock values should be stored in DynamicVariables. The semantics will be as follows:
- If the mock key has a value in the system properties, use that value. 
- If the global mock key has a value in the system properties, use that value
- Otherwise use the given value

DynamicVariables are inherited from parent threads so things should work out correctly.

**Comment by mlagutko** [comment]
Hi, Noel.

It is good idea. I wanted to introduce the feature but did not have time to
do that. Great work.

Bye, Misha,

On Mon, Feb 13, 2012 at 5:27 PM, Noel Welsh <
reply@reply.github.com

**Comment by mlagutko** [comment]
I don't think there will be race condition if we use 'parallelExecution := false'. BlueEyesServiceSpecification uses 'sequential = true' settings. So all tests run sequentially.

**Comment by jdegoes** [comment]
Most tech discussion does indeed occur in the office or through private emails. However, we can create a private list to discuss BlueEyes issues (it would be good to document it, too).

I've added you as a committer so you have full push rights (feel free to push directly to master). This entitles you to a license of JProfiler if you don't have one already. :-)

Meanwhile, I'll work on setting up a private list for the committers of BlueEyes.

Once BlueEyes reaches v1, I do have interest in writing about the framework and would want to find a co-author (in a previous life, I was a published best-selling author of books on 3D game programming).

Welcome aboard!

Regards,

John A. De Goes
Twitter: @jdegoes 
LinkedIn: http://linkedin.com/in/jdegoes

**Comment by noelwelsh** [comment]
Other open source projects I've been part have had public lists for dev. issues. This gives the general users more visibility into development plans and helps users transition to being commiters. Unless there is a good reason I think the dev. list should be public. Indeed, given the low traffic on the mailing list I don't see any reason not to use the main list for this.

**Comment by jdegoes** [comment]
That seems reasonable to me. I'll let the other devs know to use the public list for now.

Regards,

John A. De Goes
Twitter: @jdegoes 
LinkedIn: http://linkedin.com/in/jdegoes

**Comment by noelwelsh** [comment]
I guess this is redundant now.

**Pull request closed without merging**
